-- a seleção de uma query se dá pelos filtros utilizados no WHERE

SELECT  *
FROM    HR.EMPLOYEES
WHERE   DEPARTMENT_ID = 10;

SELECT  
    FIRST_NAME,
    LAST_NAME
FROM    HR.EMPLOYEES
WHERE   JOB_ID = 'IT_PROG';

SELECT
    FIRST_NAME,
    LAST_NAME
FROM    HR.EMPLOYEES
WHERE   JOB_ID = 'IT_PROG' AND DEPARTMENT_ID = 60;

SELECT
    FIRST_NAME,
    LAST_NAME
FROM    HR.EMPLOYEES
WHERE   JOB_ID = 'IT_PROG' OR JOB_ID = 'AD_VP';