SELECT
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    COMMISSION_PCT AS PORCENTAGEM_COMISSAO,
    (COMMISSION_PCT * SALARY) AS VALOR_COMISSAO
FROM    HR.EMPLOYEES
WHERE   COMMISSION_PCT IS NOT NULL;

SELECT
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    COMMISSION_PCT AS PORCENTAGEM_COMISSAO,
    (COMMISSION_PCT * SALARY) AS VALOR_COMISSAO
FROM    HR.EMPLOYEES
WHERE   COMMISSION_PCT IS NULL;