-- AND
SELECT  *
FROM    HR.EMPLOYEES
WHERE   DEPARTMENT_ID = 60
    AND JOB_ID = 'IT_PROG';

-- OR
SELECT  *
FROM    HR.EMPLOYEES
WHERE   DEPARTMENT_ID = 60
    OR  JOB_ID = 'IT_PROG';

-- NOT
SELECT  *
FROM    HR.EMPLOYEES  
WHERE   DEPARTMENT_ID NOT IN (10, 30);   